import type { ExperienceRole } from '@/types/content';

export const experience: ExperienceRole[] = [
  {
    id: 'intellifyai',
    anchor: 'exp-intellifyai',
    company: 'IntellifyAI',
    title: 'Full Stack Engineer (Contract)',
    start: 'Sep 2025',
    end: 'May 2026',
    location: 'London, UK · Remote',
    bullets: [
      'Shipped an enterprise voice AI platform to production, hitting ~1.2s median full-turn latency (STT, LLM, TTS, VAD combined) with sub-second per-stage targets.',
      'Load tested the platform at ~10 concurrent tenants with isolation verified, meeting the multi-tenancy and GDPR bar required for enterprise sign-off.',
      'Designed and built the platform RBAC system end to end on my own in TypeScript on Node.js and Express, covering role and permission modelling, enforcement across services, and the admin surface to manage it.',
      'Architected the backend from zero with the founder: Node.js and Express in TypeScript for the main platform (business logic, RBAC, admin, tenant management), Python with FastAPI for the LiveKit voice agent runtime and deployment pipelines.',
      'Validated the approach through multiple POCs before committing to the full build, then automated per-tenant Azure rollout in Python so onboarding became a repeatable pipeline rather than a manual ops job.',
      'Led a small team of senior engineers through delivery, then guided them after launch so they could own the platform once I rolled off.',
    ],
    tech: ['TypeScript', 'Node.js', 'Express', 'Next.js', 'LiveKit', 'Azure AI Foundry', 'Python', 'FastAPI', 'Docker'],
  },
  {
    id: 'mindcraft',
    anchor: 'exp-mindcraft',
    company: 'Mindcraft Labs',
    title: 'Fullstack AI Developer',
    start: 'Feb 2025',
    end: 'Sep 2025',
    location: 'Gurgaon, India · Remote',
    bullets: [
      'Converted multiple multi-step manual onboardings into chatbot and voice agent flows, collapsing human-handled intakes into self-serve conversations.',
      'Engineered three voice agent platforms on top of whitelabel providers (ElevenLabs, Retell AI), extending each in TypeScript on Node.js with custom logic, integrations, and workflow scaffolding so they fit real business processes rather than running as stock agents.',
      'Built a Sheets-to-call automation that placed bulk outbound calls, captured structured results, and triggered downstream workflows, handling ~100 calls per campaign.',
      'Shipped Node.js microservices, Python scripts, and low-code workflows across the wider automation portfolio to remove daily ops time across the business.',
      'Owned full-stack delivery on Next.js, Node.js, and Firebase in TypeScript, from data model to UI to monitoring.',
    ],
    tech: ['TypeScript', 'Node.js', 'Next.js', 'Firebase', 'Python', 'ElevenLabs', 'Retell AI'],
  },
  {
    id: 'menrva',
    anchor: 'exp-menrva',
    company: 'Menrva Technologies',
    title: 'Front-end Developer Intern',
    start: 'Oct 2023',
    end: 'Jan 2025',
    location: 'Bangalore, India · Remote',
    bullets: [
      'Delivered agile React development for product interfaces, integrating AI services via APIs with full user-management flows.',
      'Owned UI feature delivery from Figma to production, including responsive layouts and accessibility.',
      'Collaborated directly with the founder and leadership on front-end strategy, contributing to project delivery and product decisions.',
      'Recognised as Best Intern of the Quarter (Oct to Dec 2023) for shipped feature work.',
    ],
    tech: ['React', 'TypeScript', 'CSS', 'Firebase'],
  },
];
